plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
title: Technodarkness Lore Reference
description: Description
remote_theme: "mmistakes/minimal-mistakes@4.28.0"
image: ../images/

sidebar:
  nav: "docs"